#Cereal windowrule
windowrule = rounding 0, fullscreen:1
windowrule = opacity 0.93, class:^(Alacritty)$
windowrule = opacity 0.93, class:^(kitty)$
windowrule = opacity 0.93, class:^(code-oss)$
windowrule = float,class:^(xdg-desktop-portal-gtk)$ #center xdg-desktop-portal-gtk
windowrule = workspace 3, class:^(steam)$
windowrule = opacity 0.93, class:^(steam)$
windowrule = opacity 0.93, class:^(Spotify)$
windowrule = workspace 2, class:^(firefox)
windowrule = float, class:^(firefox)$,title:^(Picture-in-Picture)$
windowrule = opacity 0.93,class:^(jetbrains-.*)$
windowrule = float,class:^(dialog)$
windowrule = float,class:^(jetbrains-.*)$,title:^(win[0-9]+)$
windowrule = nofocus,class:^(jetbrains-.*)$,title:^(win[0-9]+)$
windowrule = opacity 0.93,class:^(com.heroicgameslauncher.hgl)$
windowrule = opacity 0.93,class:^(net.lutris.Lutris)$

windowrule = workspace 4, class:^(qemu-system-x86_64)$
windowrule = tile, class:^(qemu-system-x86_64)$
windowrule = fullscreen, class:^(qemu-system-x86_64)$

layerrule = blur, notifications
layerrule = ignorezero, notifications
